### ISSUE TITLE
Response doesn't include the body

### ISSUE THREAD

**Issue by rarunp04** [maciejmaciejewski/request-har#1]
Hi , 
I ran a script using this , but unfortunately the response was not captured . The message says missing headers . Are headers also to be passed ?

**Comment by maciejmaciejewski** [comment]
hey @rarunp04 
I have been using it for my API tests for quite some time and haven't noticed any issues.
Can you please show how you use this lib so I can understand your use case.

**Comment by rarunp04** [comment]
Hi @maciejmaciejewski , thanks for quick response .

My use case , using protractor (javascript)for my automation and after navigating to a URL and then capture the traffic as har file . Had used the same code present in the readme.md.
Had installed request , request-promise and request-har

Not sure if this is the correct way or this npm module is intended for the my use case
After navigation to https://www.google.com had , called the below code

`const RequestHar = require('request-har').RequestHar
const har = new RequestHar(require('request-promise').defaults({resolveWithFullResponse: true}))

let requestOptions = {
  url: 'https://www.google.com',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    foo: 'bar'
  })
}

let response = await har.request(requestOptions)

har.saveFile('./json-placeholder.har')`

**Comment by maciejmaciejewski** [comment]
I have checked your code and the issue is that the google endpoint you are hitting returns 405 which is treated as an error by request-promise library and terminates the process before har file is saved. You can get har by wrapping faulty request in try-catch block like below:
```
    try {
        let response = await har.request(requestOptions)
    } catch (error) {
        
    }
```

**Comment by rarunp04** [comment]
Thanks @maciejmaciejewski  for the update . 
Seems my use case will not support since the tests performed by me are on front end test and this package mostly focus on backend tests

Really appreciate your response

**Comment by maciejmaciejewski** [comment]
Indeed those are two distinct scenarios, my package is targeted for backend API calls. If you want to get network calls from frontend you can either implement https://www.npmjs.com/package/chrome-har
or use proxy
https://github.com/lightbody/browsermob-proxy/
